spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    driver-class-name: {{ DB_DRIVER }}
    username: {{ DB_USERNAME }}
    password: {{ DB_PASSWORD }}
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
      static-locations: file:src/main/resources/static/
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        web: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
        transaction: DEBUG


